name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend deps
        run: |
          pip install -r app/requirements.txt

      - name: Backend import test
        run: |
          cd app
          python -c "from main import app; print('Backend OK')"


  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build frontend
        run: npm run build